# Generated by Django 3.1.4 on 2020-12-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sellername', models.CharField(max_length=60)),
                ('selleremail', models.CharField(max_length=60)),
                ('sellerpass', models.CharField(max_length=250)),
            ],
        ),
    ]
