# Generated by Django 3.1.4 on 2020-12-31 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plantName', models.CharField(max_length=60)),
                ('plantImage', models.CharField(max_length=60)),
                ('plantPrice', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('nurseryId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sellers.seller')),
            ],
        ),
    ]
