# Generated by Django 3.1.4 on 2020-12-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plantImage',
            field=models.CharField(max_length=350),
        ),
    ]
