# Generated by Django 3.1.4 on 2020-12-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20201231_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plantPrice',
            field=models.DecimalField(decimal_places=4, max_digits=30, null=True),
        ),
    ]
