# Generated by Django 3.1.4 on 2020-12-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_auto_20201231_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plantPrice',
            field=models.DecimalField(decimal_places=4, max_digits=30),
        ),
    ]
