# Generated by Django 3.1.4 on 2020-12-31 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sellers', '0005_auto_20201231_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalPrice', models.DecimalField(decimal_places=4, max_digits=30)),
                ('quantity', models.BigIntegerField(null=True)),
                ('address', models.CharField(max_length=800)),
                ('phoneNumber', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=50)),
                ('orderdAt', models.DateTimeField(auto_now_add=True)),
                ('nurseryId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sellers.seller')),
                ('plantId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sellers.plant')),
                ('userId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
