# Generated by Django 3.1.4 on 2020-12-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201231_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
    ]
