# Generated by Django 3.1.4 on 2020-12-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201231_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plantName',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
